name: Build and Push to ACR

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login to ACR
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.ACR_LOGIN_SERVER }}

      # 3. Build Docker image
      - name: Build Docker Image
        run: |
          IMAGE_NAME=${{ secrets.ACR_LOGIN_SERVER }}/nextjs-app:latest
          docker build -t $IMAGE_NAME .

      # 4. Push image to ACR
      - name: Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.ACR_LOGIN_SERVER }}/nextjs-app:latest
          docker push $IMAGE_NAME
